//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda_Deportiva
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public string cod_producto { get; set; }
        public string nom_producto { get; set; }
        public int precio_producto { get; set; }
        public int cantidad_producto { get; set; }
        public string descripcion { get; set; }
        public string imagen { get; set; }
    }
}
